Build: set target (Fixes #4)
TheMightyPenguin/dessert-box pull request #5
Opened 2021-07-21 02:21 UTC by graup

Issue: #4 

This fixes the transform of the nullish coalescing operator. Not sure this is the "correct" setting.

My project with babel presets of `["@babel/preset-env", "@babel/preset-react", "@babel/preset-typescript"]` works with this.

2021-07-23 15:17 UTC, TheMightyPenguin commented
@graup Thank you so much for the contribution! Could you make this "es2018" so it also transpires the spread operator to make it easier to use to more users?

2021-07-26 06:07 UTC, graup commented
@TheMightyPenguin changed to es2018!

2021-07-27 00:18 UTC, TheMightyPenguin requested changes
💯

2021-07-27 00:19 UTC, TheMightyPenguin approved these changes
💯  (Meant to approve first and miss clicked)

2021-07-27 00:19 UTC, TheMightyPenguin commented
@graup Awesome stuff, thank you so much for your contribution! I'll create a release soon and notify you here.

2021-07-27 00:20 UTC, merged